server:
  port: 8088


spring:
  datasource:
    url: jdbc:postgresql://211.253.29.133:5433/stockatto
    username: soo
    password: devsoo
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 300000

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

